name: moviesapps
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version of the application
version: 1.0.0+1

# Dart SDK compatibility range
environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  url_launcher: ^6.1.10

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Specify the assets used in the app
  assets:
    - assets/image/notfound.png
