name: moviesapps
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Additional dependencies
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # This line ensures the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, uncomment the following lines:
  assets:
    - assets/image/
